### ISSUE TITLE
创建 vipb 安装包

### ISSUE THREAD

**Issue by nevstop** [nevstop/LabVIEW-GlobalStop-Library#1]

**Comment by nevstop** [comment]
![image](https://cloud.githubusercontent.com/assets/8196752/10752099/221f358c-7cc1-11e5-9011-05488f96a891.png)

![2015-10-27_154052](https://cloud.githubusercontent.com/assets/8196752/10752114/3e35e9dc-7cc1-11e5-8a2d-8604c61b51c3.png)

**Comment by HongsunGuo** [comment]
遥遥，为啥set stop, reset stop 这些不用call library node实现呢？

**Comment by nevstop** [comment]
这个已经很高效了，用c实现然后用CLN调用，效率低还要加载dll 还不能跨平台，不方便啊。

**Comment by nevstop** [comment]
我最近在搞 https://github.com/nevstop/Message-Framework-Library
用这个当底层做cRIO 的一整套框架，嘿嘿嘿

**Comment by HongsunGuo** [comment]
看来只有我们组用CLN。。。

**Comment by HongsunGuo** [comment]
哦 是你自己封装的一套协议吗？

**Comment by nevstop** [comment]
主要是要是复杂的就用C写了，你们组的功能多，多平台编译也方便，所以没关系的。
我写的那个是一个消息机制，生产者消费者结构而已，不过封装让每个消息用一个Vi实现。
